classDiagram

    証明通知 --> 法人 : ad&#58宛先
    証明通知 --> 個人 : ad&#58宛先
    証明通知 --> 法人 : ad&#58発行元

    法人 --> 個人 : pd&#58代表者

    class 証明通知 ["ad:証明・通知"] {
        ad:宛先
        ad:証明日
        ad:ID
        ad:名称
        ad:対象
        ad:分類
        ad:内容
        ad:値
        ad:証明開始日
        ad:証明終了日
        ad:備考
        ad:発行元
    }

    class 法人 ["pd:法人"] {
        pd:法人番号
        pd:ID群
        pd:商号または名称
        pd:商号または名称（カナ）
        pd:商号または名称（英字）
        pd:組織種別
        pd:通称
        pd:事業活動状況
        pd:説明
        pd:WebサイトURL
        pd:社員数
        pd:代表者
        pd:代表者役職名
        pd:設立年月日
        pd:事業種目
        pd:登記住所
        pd:事業所情報
        pd:連絡先情報
    }

    class 個人 ["pd:個人"] {
        pd:ID群
        pd:氏
        pd:名
        pd:氏（カナ）
        pd:名（カナ）
        pd:氏（英字）
        pd:名（英字）
        pd:氏名
        pd:氏名（カナ）
        pd:氏名（英字）
        pd:国籍
        pd:性別
        pd:生年月日
        pd:死亡年月日
        pd:備考
        pd:住所
        pd:連絡先情報
    }
