classDiagram

    報告書 --> 連絡先 : ad&#58連絡先

    class 報告書 ["ad:報告書"] {
        ad:カタログ名
        ad:カタログ内容
        ad:カタログの主要トピック
        ad:カタログテーマ
        ad:親カタログ名
        ad:子カタログ名
        ad:カタログ発行者
        ad:カタログ更新日
        ad:カタログ言語
        ad:ID
        ad:タイトル
        ad:サブタイトル
        ad:バージョン
        ad:説明
        ad:タイプ
        ad:テーマ
        ad:キーワード/タグ
        ad:対象地域
        ad:対象期間
        ad:更新頻度
        ad:フォーマット
        ad:作成者
        ad:関係者
        ad:連絡先
        ad:説明ページURL
        ad:ダウンロードURL
        ad:データサービスの可否
        ad:エンドポイントURL
        ad:エンドポイント説明
        ad:サイズ
        ad:ライセンス
        ad:権利
        ad:発行日
        ad:更新日
        ad:状況
        ad:言語
    }

    class 連絡先 ["pd:連絡先"] {
        pd:連絡先名称
        pd:連絡先用途
        pd:連絡先電話番号
        pd:連絡先メールアドレス
        pd:連絡先URL
        pd:連絡先SNS
        pd:連絡先住所
        pd:連絡先備考
    }
