classDiagram

    制度 --> 連絡先 : pd&#58連絡先情報

    class 制度 ["ad:制度"] {
        ad:制度所管組織
        ad:タイトル（制度名）
        ad:サブタイトル（通称）
        ad:制度番号
        ad:元制度番号
        ad:制度変更区分
        ad:根拠法令
        ad:地域群
        ad:地域
        ad:概要
        ad:内容
        ad:対象者
        ad:用途・対象物
        ad:収入条件
        ad:家族構成条件
        ad:対象者条件
        ad:従業員条件
        ad:資本金条件
        ad:創業年条件
        ad:給付上限額
        ad:最大金利
        ad:借入限度額
        ad:償還期限
        ad:最大補助率
        ad:費用
        ad:予算枠の有無
        ad:申請届出方法
        ad:募集時期
        ad:公募開始日
        ad:公募終了日
        ad:公募備考
        ad:手続書類
        ad:電子申請の有無
        ad:添付ファイルの名称
        ad:添付ファイル名
        ad:詳細参照先
        ad:詳細URL
        ad:標準産業分類
        ad:ステージとアクション
        ad:事業ステージ
        ad:お困りごと
        ad:サービス種別
        ad:災害名
        ad:キーワード
        ad:実施組織・支援機関
        ad:お問い合わせ先
        ad:お問い合わせ一覧
        pd:連絡先情報
        ad:公開開始日
        ad:公開終了日
        ad:最終更新日
        ad:表示優先度
    }

    class 連絡先 ["pd:連絡先"] {
        pd:連絡先名称
        pd:連絡先用途
        pd:連絡先電話番号
        pd:連絡先メールアドレス
        pd:連絡先URL
        pd:連絡先SNS
        pd:連絡先住所
        pd:連絡先備考
    }
