classDiagram

    イベント --> 連絡先 : pd&#58連絡先情報
    イベント --> 住所 : pd&#58開催場所住所

    連絡先 --> 住所 : pd&#58連絡先住所

    class イベント ["pd:イベント"] {
        pd:ID
        pd:イベント名
        pd:イベント名（カナ）
        pd:イベント名（英字）
        pd:通称
        pd:サブタイトル
        pd:説明
        pd:サブイベント
        pd:イベント種類
        pd:イベントURL
        pd:状態
        pd:キーワード
        pd:タグ
        pd:開催パターン
        pd:開始日
        pd:終了日
        pd:開始時刻
        pd:終了時刻
        pd:日時説明
        pd:開催場所
        pd:開催場所住所
        pd:開催施設
        pd:アクセス方法
        pd:Web開催
        pd:主催団体
        pd:共催団体
        pd:関連団体
        pd:対象者
        pd:定員
        pd:料金有無
        pd:駐車場有無
        pd:連絡先情報
    }

    class 住所 ["pd:住所"] {
        pd:全国地方公共団体コード
        pd:町字ID
        pd:都道府県
        pd:市区町村（郡）
        pd:町字
        pd:番地以下
        pd:建物名等（方書）
        pd:連結表記
        pd:郵便番号
        pd:国
        pd:町字以下
    }

    class 連絡先 ["pd:連絡先"] {
        pd:連絡先名称
        pd:連絡先用途
        pd:連絡先電話番号
        pd:連絡先メールアドレス
        pd:連絡先URL
        pd:連絡先SNS
        pd:連絡先住所
        pd:連絡先備考
    }

    class アクセシビリティ ["pd:アクセシビリティ"] {
        pd:車椅子可
        pd:車椅子貸出
        pd:ツエ貸出
        pd:バリアフリートイレ
        pd:スロープ、エレベータ、エスカレータ
        pd:点字ブロック等の移動支援
        pd:点字や読上による支援
        pd:盲導犬・介助犬・聴導犬同伴
        pd:字幕
        pd:筆談対応
        pd:優先駐車場
        pd:オストメイト対応トイレ
        pd:子供トイレ
        pd:授乳室
        pd:おむつ替えコーナー
        pd:飲食可否
        pd:ベビーカー貸出
        pd:ベビーカー利用可
        pd:備考
    }

    class 子供預かり情報 ["pd:子供預かり情報"] {
        pd:料金有無
        pd:料金説明
        pd:最少年齢
        pd:最少月齢
        pd:最大年齢
        pd:開所時間
        pd:閉所時間
        pd:備考
    }
