classDiagram

    申請_士業法人 --> 法人申請基本情報A票 : ad&#58法人申請基本情報（A票）
    申請_士業法人 --> 法人申請内容B票 : ad&#58申請内容（B票）
    申請_士業法人 --> 財務情報C票 : ad&#58財務情報（C票）
    申請_士業法人 --> 士業法人役員一覧D票 : ad&#58役員一覧（D票）
    申請_士業法人 --> 主要株主E票 : ad&#58主要株主（E票）
    申請_士業法人 --> 事業所一覧F票 : ad&#58事業所一覧（F票）
    申請_士業法人 --> 資格保有者G票 : ad&#58資格保有者（従業員）一覧（G票）

    法人申請基本情報A票 --> 法人 : ad&#58宛先
    法人申請基本情報A票 --> 法人 : ad&#58申請者
    法人申請基本情報A票 --> 法人 : ad&#58委任者
    法人申請基本情報A票 --> 個人 : ad&#58委任者
    法人申請基本情報A票 --> 連絡先 : ad&#58連絡先

    士業法人役員一覧D票 --> "0..n" 個人 : ad&#58役員

    主要株主E票 --> "0..n" 法人 : ad&#58株主
    主要株主E票 --> "0..n" 個人 : ad&#58株主

    事業所一覧F票 --> 事業所 : ad&#58事業所

    資格保有者G票 --> 個人 : ad&#58資格保有者
    資格保有者G票 --> 事業所 : ad&#58所属事務所

    法人 --> 個人 : pd&#58代表者
    法人 --> 連絡先 : pd&#58連絡先情報
    法人 --> "0..n" 事業所 : pd&#58事業所情報

    個人 --> 連絡先 : pd&#58連絡先情報

    class 申請_士業法人 ["ad:申請（士業法人）"] {
        ad:法人申請基本情報（A票）
        ad:申請内容（B票）
        ad:財務情報（C票）
        ad:役員一覧（D票）
        ad:主要株主（E票）
        ad:事業所一覧（F票）
        ad:資格保有者（従業員）一覧（G票）
    }

    class 法人申請基本情報A票 ["ad:法人申請基本情報（A票）"] {
        ad:宛先
        ad:申請日
        ad:連絡先
        ad:申請者
        ad:委任者
        ad:委任者の役割
        ad:委任内容
    }

    class 法人申請内容B票 ["ad:法人申請内容（B票）"] {
        ad:名称
        ad:概要
        ad:内容
        ad:更新年月日
    }

    class 財務情報C票 ["ad:財務情報（C票）"] {
        ad:決算年月日
        ad:事業期間開始日
        ad:事業期間終了日
        ad:期末従業員数
        ad:資産合計
        ad:流動資産合計
        ad:現金及び預金
        ad:受取手形
        ad:売掛金
        ad:有価証券
        ad:棚卸資産
        ad:その他流動資産合計
        ad:前払金
        ad:短期貸付金
        ad:貸倒引当金
        ad:固定資産合計
        ad:有形固定資産合計
        ad:土地
        ad:無形固定資産合計
        ad:その他固定資産合計
        ad:貸付金合計
        ad:負債合計
        ad:流動負債合計
        ad:支払手形
        ad:買掛金
        ad:短期借入金
        ad:その他流動負債合計
        ad:未払金
        ad:前受金
        ad:預り金
        ad:固定負債合計
        ad:長期借入金
        ad:純資産合計
        ad:資本準備金
        ad:売上高
        ad:売上原価
        ad:売上原価内減価償却
        ad:労務費
        ad:売上純利益
        ad:販売費及び一般管理費
        ad:販管費内減価償却費
        ad:人件費
        ad:営業利益
        ad:営業外収益
        ad:営業外費用
        ad:経常利益
        ad:特別利益
        ad:特別損失
        ad:税引前当期純利益
        ad:当期純利益
    }

    class 士業法人役員一覧D票 ["ad:士業法人役員一覧（D票）"] {
        ad:役員表記入日
        ad:役員
        ad:資格コード
        ad:資格名称
        ad:登録番号
        ad:登録年月日
        ad:資格有効期限
        ad:所属事務所
    }

    class 主要株主E票 ["ad:主要株主（E票）"] {
        ad:株主表記入日
        ad:株主
        ad:出資比率
        ad:大企業区分
    }

    class 事業所一覧F票 ["ad:事業所一覧（F票）"] {
        ad:事業所一覧記入日
        ad:事業所番号
        ad:事業所
        ad:業種コード
    }

    class 資格保有者G票 ["ad:資格保有者（G票）"] {
        ad:資格コード
        ad:資格名称
        ad:資格保有者
        ad:登録番号
        ad:登録年月日
        ad:資格有効期限
        ad:所属事務所
    }

    class 法人 ["pd:法人"] {
        pd:法人番号
        pd:ID群
        pd:商号または名称
        pd:商号または名称（カナ）
        pd:商号または名称（英字）
        pd:組織種別
        pd:通称
        pd:事業活動状況
        pd:説明
        pd:WebサイトURL
        pd:社員数
        pd:代表者
        pd:代表者役職名
        pd:設立年月日
        pd:事業種目
        pd:登記住所
        pd:事業所情報
        pd:連絡先情報
    }

    class 個人 ["pd:個人"] {
        pd:ID群
        pd:氏
        pd:名
        pd:氏（カナ）
        pd:名（カナ）
        pd:氏（英字）
        pd:名（英字）
        pd:氏名
        pd:氏名（カナ）
        pd:氏名（英字）
        pd:国籍
        pd:性別
        pd:生年月日
        pd:死亡年月日
        pd:備考
        pd:住所
        pd:連絡先情報
    }

    class 事業所 ["pd:事業所"] {
        pd:ID
        pd:名称
        pd:事業所住所
        pd:説明
    }

    class 連絡先 ["pd:連絡先"] {
        pd:連絡先名称
        pd:連絡先用途
        pd:連絡先電話番号
        pd:連絡先メールアドレス
        pd:連絡先URL
        pd:連絡先SNS
        pd:連絡先住所
        pd:連絡先備考
    }
