classDiagram

    公告管理情報 --> 入札公告 : ad&#58入札公告
    公告管理情報 --> 調達予定の公告 : ad&#58調達予定の公告
    公告管理情報 --> 落札公告 : ad&#58落札公告
    公告管理情報 --> 訂正公告 : ad&#58訂正公告
    公告管理情報 --> 関連参加資格等の公告 : ad&#58関連参加資格等の公告

    class 公告管理情報 ["ad:公告管理情報"] {
        ad:公示種別
        ad:カテゴリー
        ad:公示日
        ad:契約担当官
        ad:調達機関コード
        ad:組織名
        ad:機関種別名
        ad:都道府県市町村コード
        ad:入札公告番号
        ad:号番号
        ad:訂正・取消区分
        ad:区分
        ad:変更公示ID

        ad:入札公告
        ad:調達予定の公告
        ad:落札公告
        ad:訂正公告
        ad:関連参加資格等の公告
    }

    class 入札公告 ["ad:入札公告"] {
        ad:品目分類番号
        ad:件名
        ad:件名（英語）
        ad:数量
        ad:単位
        ad:公告
        ad:納入期限日
        ad:納入期限日備考
        ad:履行期間
        ad:履行場所
        ad:入札方法
        ad:追加工事
        ad:工事実施形態
        ad:参加資格
        ad:参加資格種類
        ad:参加希望地域
        ad:参加者条件
        ad:申請書提出郵便番号
        ad:申請書提出住所
        ad:申請書提出組織
        ad:申請書提出担当者
        ad:申請書提出電話番号
        ad:申請書提出方法
        ad:入札書提出郵便番号
        ad:入札書提出住所
        ad:入札書提出組織
        ad:入札書提出担当者
        ad:入札書提出電話番号
        ad:契約条項を示す場所
        ad:入札説明書交付場所
        ad:公告問合せ先
        ad:入札説明書交付方法
        ad:説明会日時
        ad:説明会場所
        ad:入札期限日
        ad:入札書提出方法
        ad:開札日
        ad:開札場所
        ad:言語
        ad:通貨
        ad:入札保証金
        ad:契約保証金
        ad:入札者に要求される事項
        ad:入札の無効
        ad:契約書作成の要否
        ad:落札者の決定方法
        ad:配置予定技術者の確認
        ad:手続きにおける交渉の有無
        ad:電子調達システムの利用
        ad:その他
        ad:一般競争参加資格の認定を受けていない者の参加
        ad:詳細
        ad:公告情報（url）
    }

    class 調達予定の公告 ["ad:調達予定の公告"] {
        ad:品目分類番号
        ad:件名
        ad:件名（英語）
        ad:数量
        ad:単位
        ad:入札公告（公示）の予定時期
        ad:予定価格
    }

    class 落札公告 ["ad:落札公告"] {
        ad:品目分類番号
        ad:件名
        ad:件名（英語）
        ad:数量
        ad:単位
        ad:調達方法
        ad:契約方式
        ad:落札者
        ad:落札者法人番号
        ad:落札者氏名
        ad:落札者住所
        ad:落札価格
        ad:随意契約理由
        ad:指名業者名
        ad:落札方式
        ad:予定価格
    }

    class 訂正公告 ["ad:訂正公告"] {
        ad:品目分類番号
        ad:件名
        ad:件名（英語）
        ad:数量
        ad:単位
        ad:訂正項目
        ad:訂正前情報
        ad:訂正後情報
    }

    class 関連参加資格等の公告 ["ad:関連参加資格等の公告"] {
        ad:品目分類番号
        ad:件名
        ad:件名英語
        ad:数量
        ad:単位
        ad:関連資格
        ad:必須参加資格
        ad:関連参加資格
        ad:その他条件
    }
