classDiagram

    事例 --> 連絡先 : pd&#58連絡先情報
    事例 --> 住所 : ad&#58事例の場所
    事例 --> 法人 : ad&#58対象組織

    法人 --> 連絡先 : pd&#58連絡先情報
    法人 --> 住所 : pd&#58登記住所

    連絡先 --> 住所 : pd&#58連絡先住所

    class 事例 ["ad:事例"] {
        ad:タイトル
        ad:サブタイトル
        ad:事例実施年
        ad:事例の場所
        ad:対象組織
        ad:行政サービス分類
        ad:テーマ
        ad:キーワード
        ad:取り組みの概要
        ad:取り組み理由
        ad:目的
        ad:挑戦したこと
        ad:取り組み内容
        ad:学んだこと
        ad:成果
        ad:導入での工夫
        ad:制約条件
        ad:普及
        ad:持続させる仕組み
        ad:評価の方法
        ad:利用した制度
        ad:協力者
        ad:イメージタイトル
        ad:イメージファイル
        ad:イメージのライセンス
        ad:ビデオタイトル
        ad:ビデオURL
        ad:ビデオのライセンス
        ad:関連URL
        ad:関連事例
        pd:連絡先情報
        ad:ID
        ad:公開日
        ad:最終更新日
    }

    class 事例集 ["ad:事例集"] {
        ad:データカタログ名
        ad:データカタログ説明
        ad:データカタログ作成者
        ad:発行年
        ad:ライセンス
        ad:言語
    }

    class 法人 ["pd:法人"] {
        pd:法人番号
        pd:ID群
        pd:商号または名称
        pd:商号または名称（カナ）
        pd:商号または名称（英字）
        pd:組織種別
        pd:通称
        pd:事業活動状況
        pd:説明
        pd:WebサイトURL
        pd:社員数
        pd:代表者
        pd:代表者役職名
        pd:設立年月日
        pd:事業種目
        pd:登記住所（
        pd:事業所情報
        pd:連絡先情報
    }

    class 住所 ["pd:住所"] {
        pd:全国地方公共団体コード
        pd:町字ID
        pd:都道府県
        pd:市区町村（郡）
        pd:町字
        pd:番地以下
        pd:建物名等（方書）
        pd:連結表記
        pd:郵便番号
        pd:国
        pd:町字以下
    }

    class 連絡先 ["pd:連絡先"] {
        pd:連絡先名称
        pd:連絡先用途
        pd:連絡先電話番号
        pd:連絡先メールアドレス
        pd:連絡先URL
        pd:連絡先SNS
        pd:連絡先住所
        pd:連絡先備考
    }
    