classDiagram

見積情報 --> "0..*" 役務明細情報_明細毎 : ad&#58役務明細情報
見積情報 --> "0..*" 経費明細情報_明細毎 : ad&#58経費明細情報
見積情報 --> "0..*" 諸費用明細情報_明細毎 : ad&#58諸費用明細情報

    class 見積情報 ["ad:見積情報"] {
        ad:宛先組織名
        ad:案件番号
        ad:件名
        ad:作成日
        ad:見積有効期限
        ad:法人番号
        ad:法人名
        ad:法人住所
        ad:法人担当所属
        ad:見積小計額
        ad:見積税率
        ad:見積税額
        ad:見積金額
        ad:備考
        ad:役務明細情報
        ad:経費明細情報
        ad:諸費用明細情報
    }

    class 役務明細情報_明細毎 ["ad:役務明細情報"] {
        ad:役務分類
        ad:役務細分類
        ad:役割
        ad:ランク
        ad:単価
        ad:数量
        ad:単位
        ad:明細金額
        ad:委託先法人名
        ad:委託先法人番号
        ad:再々委託フラグ
        ad:備考
    }

    class 経費明細情報_明細毎 ["ad:経費明細情報"] {
        ad:経費分類
        ad:品名
        ad:品名詳細
        ad:単価
        ad:数量
        ad:単位
        ad:明細金額
        ad:備考
    }

    class 諸費用明細情報_明細毎 ["ad:諸費用明細情報"] {
        ad:諸費用分類
        ad:諸費用名
        ad:詳細
        ad:単価
        ad:数量
        ad:単位
        ad:明細金額
        ad:備考
    }
